-- Migration: 002_drop_fk_tc_tx.sql
--
-- Purpose:
--   Drop the fk_tc_tx foreign key constraint from the tokenchain table.
--
-- Why:
--   PledgeV2 inserts tokenchain rows keyed by mainTxID (the main transfer transaction ID)
--   BEFORE that transaction is persisted into the transactions table. The main transaction
--   only lands in transactions via PersistPostConsensus, which runs after full consensus
--   completes. fk_tc_tx (tokenchain.transaction_id REFERENCES transactions.id) is checked
--   at commit time (DEFERRABLE INITIALLY DEFERRED) and fires because mainTxID does not
--   exist in transactions at pledge time, causing SQLSTATE 23503.
--
--   Pledge and unpledge rows are state transitions tied to mainTxID, not independent
--   transactions. The FK does not hold for pledge entries.
--
-- Idempotent:
--   Safe to run multiple times. Uses IF EXISTS guard.
--
-- How to run:
--   psql -h <host> -U <user> -d <database> -f 002_drop_fk_tc_tx.sql

ALTER TABLE tokenchain DROP CONSTRAINT IF EXISTS fk_tc_tx;
