// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.1
// source: sky_third_party.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QRInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *QRInfoRequest) Reset() {
	*x = QRInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sky_third_party_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRInfoRequest) ProtoMessage() {}

func (x *QRInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sky_third_party_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRInfoRequest.ProtoReflect.Descriptor instead.
func (*QRInfoRequest) Descriptor() ([]byte, []int) {
	return file_sky_third_party_proto_rawDescGZIP(), []int{0}
}

func (x *QRInfoRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type QRInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Purpose string `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *QRInfoResponse) Reset() {
	*x = QRInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sky_third_party_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRInfoResponse) ProtoMessage() {}

func (x *QRInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sky_third_party_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRInfoResponse.ProtoReflect.Descriptor instead.
func (*QRInfoResponse) Descriptor() ([]byte, []int) {
	return file_sky_third_party_proto_rawDescGZIP(), []int{1}
}

func (x *QRInfoResponse) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *QRInfoResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_sky_third_party_proto protoreflect.FileDescriptor

var file_sky_third_party_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x6b, 0x79, 0x5f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22,
	0x29, 0x0a, 0x0d, 0x51, 0x52, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x44, 0x0a, 0x0e, 0x51, 0x52,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x32, 0x54, 0x0a, 0x14, 0x53, 0x6b, 0x79, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x51,
	0x52, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x51,
	0x52, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x51, 0x52, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74, 0x66, 0x65, 0x78, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sky_third_party_proto_rawDescOnce sync.Once
	file_sky_third_party_proto_rawDescData = file_sky_third_party_proto_rawDesc
)

func file_sky_third_party_proto_rawDescGZIP() []byte {
	file_sky_third_party_proto_rawDescOnce.Do(func() {
		file_sky_third_party_proto_rawDescData = protoimpl.X.CompressGZIP(file_sky_third_party_proto_rawDescData)
	})
	return file_sky_third_party_proto_rawDescData
}

var file_sky_third_party_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sky_third_party_proto_goTypes = []interface{}{
	(*QRInfoRequest)(nil),  // 0: protos.QRInfoRequest
	(*QRInfoResponse)(nil), // 1: protos.QRInfoResponse
}
var file_sky_third_party_proto_depIdxs = []int32{
	0, // 0: protos.SkyThirdPartyService.GetQRInfo:input_type -> protos.QRInfoRequest
	1, // 1: protos.SkyThirdPartyService.GetQRInfo:output_type -> protos.QRInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sky_third_party_proto_init() }
func file_sky_third_party_proto_init() {
	if File_sky_third_party_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sky_third_party_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QRInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sky_third_party_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QRInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sky_third_party_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sky_third_party_proto_goTypes,
		DependencyIndexes: file_sky_third_party_proto_depIdxs,
		MessageInfos:      file_sky_third_party_proto_msgTypes,
	}.Build()
	File_sky_third_party_proto = out.File
	file_sky_third_party_proto_rawDesc = nil
	file_sky_third_party_proto_goTypes = nil
	file_sky_third_party_proto_depIdxs = nil
}
