package core

import (
	"bytes"
	"fmt"

	"github.com/google/uuid"
	"github.com/rubixchain/rubixgoplatform/types/models"
)

// MintedChild reports one server-generated child NFT ID back to the caller.
type MintedChild struct {
	ParentNFTId string `json:"parentNFTId"`
	ChildNFTId  string `json:"childNFTId"`
}

// expandChildMintEntries turns child-mint requests into normal execute and
// deploy entries that the rest of the pipeline already understands.
//
// For each NFT entry with ParentNFTId set, it adds an execute entry for the
// parent (once per parent) and a deploy entry for a new child NFT. The child's
// ID is generated by IPFS-adding (parentNFTId + uuid). The child's value comes
// from the request when set, otherwise it inherits the parent's current value.
//
// Rejects:
//   - transferNftOwnership=true combined with any child-mint entry.
//   - a parent named in both a regular entry and as a child-mint target.
//   - a parent that does not exist locally.
//
// Ownership of the parent is checked later by QueryAndLockForExecution.
func (c *Core) expandChildMintEntries(request *models.TransactionRequest) ([]MintedChild, error) {
	if request == nil || len(request.Tokens.NFT) == 0 {
		return nil, nil
	}

	// Nothing to do if no entry asks for a child mint.
	hasChildMint := false
	for _, n := range request.Tokens.NFT {
		if n.ParentNFTId != "" {
			hasChildMint = true
			break
		}
	}
	if !hasChildMint {
		return nil, nil
	}

	if request.Tokens.TransferNFTOwnership {
		return nil, fmt.Errorf("child-mint cannot be combined with transferNftOwnership=true")
	}

	// Track parents named directly via NFTId so we can catch the case where
	// the same NFT is asked to be executed twice (once explicitly and once
	// implicitly as a child-mint parent).
	explicitParents := make(map[string]struct{})
	for _, n := range request.Tokens.NFT {
		if n.ParentNFTId == "" && n.NFTId != "" {
			explicitParents[n.NFTId] = struct{}{}
		}
	}

	// Look up each unique parent in the wallet to confirm it exists and to
	// grab its current value for inheritance.
	parentValues := make(map[string]float64)
	for _, n := range request.Tokens.NFT {
		if n.ParentNFTId == "" {
			continue
		}
		if _, seen := parentValues[n.ParentNFTId]; seen {
			continue
		}
		if _, clash := explicitParents[n.ParentNFTId]; clash {
			return nil, fmt.Errorf("parent NFT %s appears as both an explicit execute target and a child-mint parent in the same request", n.ParentNFTId)
		}
		tok, err := c.w.GetTokenByTokenID(n.ParentNFTId)
		if err != nil {
			return nil, fmt.Errorf("parent NFT %s not found in wallet: %w", n.ParentNFTId, err)
		}
		parentValues[n.ParentNFTId] = tok.TokenValue
	}

	// Record the order in which parents were first referenced so we add
	// execute entries in a stable, predictable order.
	parentOrder := make([]string, 0, len(parentValues))
	seenParent := make(map[string]struct{})
	for _, n := range request.Tokens.NFT {
		if n.ParentNFTId == "" {
			continue
		}
		if _, seen := seenParent[n.ParentNFTId]; seen {
			continue
		}
		seenParent[n.ParentNFTId] = struct{}{}
		parentOrder = append(parentOrder, n.ParentNFTId)
	}

	expanded := make([]models.NFTInfo, 0, len(request.Tokens.NFT)+len(parentOrder))

	// One execute entry per distinct parent. Value is left at 0 so the
	// downstream execute branch falls back to the parent's stored value.
	for _, p := range parentOrder {
		expanded = append(expanded, models.NFTInfo{NFTId: p})
	}

	// Walk the original list: keep regular entries as-is, turn each child-mint
	// entry into a deploy entry with a server-generated ID.
	mintedChildren := make([]MintedChild, 0)
	for _, n := range request.Tokens.NFT {
		if n.ParentNFTId == "" {
			expanded = append(expanded, n)
			continue
		}

		// Generate the child NFT ID: IPFS-add of parentNFTId + uuid.
		childUUID := uuid.New().String()
		payload := []byte(n.ParentNFTId + childUUID)
		childID, err := IpfsAddWithBackoff(c.ipfs, bytes.NewReader(payload))
		if err != nil {
			return nil, fmt.Errorf("failed to IPFS-add child NFT payload for parent %s: %w", n.ParentNFTId, err)
		}

		// Child inherits parent value when the request omits it.
		childValue := n.Value
		if childValue == 0 {
			childValue = parentValues[n.ParentNFTId]
		}

		// Leave ParentNFTId empty on the synthesized entry — it's a finished
		// deploy entry now, not something to expand again.
		expanded = append(expanded, models.NFTInfo{
			NFTId: childID,
			Value: childValue,
			Data:  n.Data,
		})

		mintedChildren = append(mintedChildren, MintedChild{
			ParentNFTId: n.ParentNFTId,
			ChildNFTId:  childID,
		})
	}

	request.Tokens.NFT = expanded
	return mintedChildren, nil
}
