
[core]
node_index = 0
network_mode = "localnet"
enable_trusted_network = true

[db]
host = "localhost"
port = 5500
username = "rubix"
password = "rubixpass"
db_name = "rubix"

[db.config]
max_connections = 50
min_connections = 5
max_connection_lifetime_seconds = 1
max_connection_idletime_seconds = 1
statement_timeout_seconds = 5

[ipfs]
mainnet_bootstrap_nodes = [
	"/ip4/161.35.169.251/tcp/4001/p2p/12D3KooWPhZEYEw4jG3kSRuwgMEHcVt7KMkm1ui2ddu4fgSgwvDq",
	"/ip4/103.127.158.120/tcp/4001/p2p/12D3KooWSQ94HRDzFf6W2rp7P8gzP6efZQHTaSU8uaQjskVBHiWP",
	"/ip4/172.104.191.191/tcp/4001/p2p/12D3KooWFudnWZY1v1m4YXCzDWZSbNt7nvf5F42uzM6vErZ4NwqJ",
]
testnet_bootstrap_nodes = [
	"/ip4/103.209.145.177/tcp/4001/p2p/12D3KooWD8Rw7Fwo4n7QdXTCjbh6fua8dTqjXBvorNz3bu7d9xMc",
	"/ip4/98.70.52.158/tcp/4001/p2p/12D3KooWQyWFABF3CKFnzX85hf5ZwrT5zPsy4rWHdGPZ8bBpRVCK",
	"/ip4/20.244.16.143/tcp/4001/p2p/12D3KooWAydFDJeSW5qupmp3AjRxc82Dq1AnjfJT1zwy4hg2TuNn",
	"/ip4/40.81.232.217/tcp/4001/p2p/12D3KooWK6V21GQotbub3cfgb5qAK1uUoUGPexf3vsLqw6yBJfen",
]
localnet_bootstrap_nodes = []
