[core]
node_index = 1
network_mode = "localnet"
enable_trusted_network = false

[db]
host = "localhost"
port = 5500
username = "rubix"
password = "rubixpass"
db_name = "rubix"

[db.config]
max_connections = 10
min_connections = 1
max_connection_lifetime_seconds = 1
max_connection_idletime_seconds = 1
statement_timeout_seconds = 5

[ipfs]
mainnet_bootstrap_nodes = [
	"/ip4/161.35.169.251/tcp/4001/p2p/12D3KooWPhZEYEw4jG3kSRuwgMEHcVt7KMkm1ui2ddu4fgSgwvDq", 
	"/ip4/103.127.158.120/tcp/4001/p2p/12D3KooWSQ94HRDzFf6W2rp7P8gzP6efZQHTaSU8uaQjskVBHiWP", 
	"/ip4/172.104.191.191/tcp/4001/p2p/12D3KooWFudnWZY1v1m4YXCzDWZSbNt7nvf5F42uzM6vErZ4NwqJ",
]
testnet_bootstrap_nodes = [
	"/ip4/103.209.145.177/tcp/4011/p2p/12D3KooWKAHAYEjjckeWi2s3oCnvkbTJX3x6fV3HZbjMEVzMfJeL",
	"/ip4/98.70.52.158/tcp/4001/p2p/12D3KooWNrfpqpSWi4N1WL9Xv8j87hm7nBMqJ3vWWp3qJ3d2MJp8 ",
]
localnet_bootstrap_nodes = []
